openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
paths:
  /user:
    post:
      operationId: createUserTest
      parameters:
        - in: header
          name: x-api-key
          required: true
          schema:
            type: string
            minLength: 10
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - age
              properties:
                name:
                  type: string
                  minLength: 3
                age:
                  type: integer
                  minimum: 18
                email:
                  type: string
                  format: email
